---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: hotelwebappdeployment
spec:
 replicas: 1
 strategy: 
    type: Recreate
 selector: 
   matchLabels: 
     app: hotelwebapp
 template:
  metadata:
   name: hotelwebapppod
   labels:
     app: hotelwebapp	 
  spec: 
    containers:
    - name: hotelwebappcontainer
      image: bhanuprakashece410/hotelwebapp
      ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
 name: hotelwebappsvc
spec:
  type: ClusterIP
  selector:
   app: hotelwebapp
  ports:
   - port: 80
     targetPort: 8080
...
